---@meta

---@class packer.PluginSpec
---@field [1] string # URL to plugin
---@field disable? boolean # Mark a plugin as inactive
---@field as? string # Specifies an alias under which to install the plugin
---@field installer? function # Specifies custom installer. See "custom installers" below.
---@field updater? function # Specifies custom updater. See "custom installers" below.
---@field after? string | string[] # Specifies plugins to load before this plugin. See "sequencing" below
---@field rtp? string # Specifies a subdirectory of the plugin to add to runtimepath.
---@field opt? boolean # Manually marks a plugin as optional.
---@field bufread? boolean # Manually specifying if a plugin needs BufRead after being loaded
---@field branch? string # Specifies a git branch to use
---@field tag? string # Specifies a git tag to use. Supports '*' for "latest tag"
---@field commit? string # Specifies a git commit to use
---@field lock? boolean # Skip updating this plugin in updates/syncs. Still cleans.
---@field run? string | function | table # Post-update/install hook. See "update/install hooks".
---@field requires? string | string[] # Specifies plugin dependencies. See "dependencies".
---@field rocks? string | string[] # Specifies Luarocks dependencies for the plugin
---@field config? string | function # Specifies code to run after this plugin is loaded.
---@field setup? string | function # implies `opt = true` Specifies code to run before this plugin is loaded even the plugin is waiting for other conditions.
-- The following keys all imply lazy-loading and imply opt = true
---@field cmd? string | string[] # Specifies commands which load this plugin. Can be an autocmd pattern.
---@field ft? string | string[] # Specifies filetypes which load this plugin.
---@field keys? string | string[] # Specifies maps which load this plugin. See "Keybindings".
---@field event? string | string[] # Specifies autocommand events which load this plugin.
---@field fn? string | string[] # Specifies functions which load this plugin.
---@field cond? string | function | (string | function)[] # Specifies a conditional test to load this plugin
---@field module? string | string[] # Specifies Lua module names for require. When requiring a string which starts with one of these module names, the plugin will be loaded.
---@field module_pattern? string | string[] -- Specifies Lua pattern of Lua module names for require. When requiring a string which matches one of these patterns, the plugin will be loaded.
